baseURL = "https://morozovvaa.github.io/portfolio2/"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "Diana Morozova"
theme = "hugo-coder"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Diana Morozova"
  description = "Студенческое портфолио"
  keywords = "portfolio,student,programming"
  info = ["Студентка", "Информатика"]
  avatarURL = "images/avatar.jpg"
  dateFormat = "2 January 2006"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"
  
  # Цветовая схема
  colorScheme = "auto"
  hideColorSchemeToggle = false
  
  since = 2024
  
  # Скрыть даты на страницах (если нужно)
  hideDate = true

# Таксономии (если будешь использовать)
[taxonomies]
  category = "categories"
  tag = "tags"

# Социальные ссылки
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/morozovvaa/"

# Меню навигации
[[menu.main]]
  name = "О себе"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "1 курс"
  weight = 2
  url = "1st/"

[[menu.main]]
  name = "2 курс"
  weight = 3
  url = "2nd/"

[[menu.main]]
  name = "3 курс"
  weight = 4
  url = "3rd/"

[[menu.main]]
  name = "4 курс"
  weight = 5
  url = "4th/"

[[menu.main]]
  name = "Модули"
  weight = 6
  url = "modules/"

[[menu.main]]
  name = "Практики"
  weight = 7
  url = "pract/"

[[menu.main]]
  name = "Курсовые"
  weight = 8
  url = "kurs/"
